abort backup if postgres is busy

diff --git a/bin/diskette b/bin/diskette
--- a/bin/diskette
+++ b/bin/diskette
@@ -2,6 +2,9 @@
 
 REPO_ROOT=${REPO_ROOT:-"/srv/diskette"}
 
+export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
+export DBUS_SESSION_BUS_ADDRESS="${DBUS_SESSION_BUS_ADDRESS:-unix:path=$XDG_RUNTIME_DIR/bus}"
+
 QUADLET_DIR=${QUADLET_DIR:-"$HOME/.config/containers/systemd"}
 SYSTEMD_DIR=${SYSTEMD_DIR:-"$HOME/.config/systemd/user"}
 ENV_FILE="$REPO_ROOT/.env"
@@ -120,7 +123,8 @@ cmd_update() {
 
 cmd_backup() {
 	info "Dumping Postgres databases"
-	podman exec postgres pg_dumpall -U postgres >/srv/appdata/postgres/backup/all-databases.sql
+	podman exec postgres pg_dumpall -U postgres >/srv/appdata/postgres/backup/all-databases.sql \
+		|| error "pg_dumpall failed. Aborting backup ..."
 
 	info "Running restic backup"
 	restic backup --tag diskette --host fd0 /srv/appdata/jellyfin/config /srv/appdata/syncthing /srv/media /srv/appdata/postgres/backup
